name: Feature request
description: A new kind of paddlin'
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: The idea
      description: What should exist that doesn't?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why it slaps
      description: How does this make the match more fun?
    validations:
      required: true
